// backend/src/utils/permissions.js

const PERMISSIONS = {
    USER_CREATE: 'USER_CREATE',
    USER_READ: 'USER_READ',
    USER_UPDATE: 'USER_UPDATE',
    USER_STATUS_UPDATE: 'USER_STATUS_UPDATE',

    PATIENT_CREATE: 'PATIENT_CREATE',
    PATIENT_READ: 'PATIENT_READ',
    PATIENT_UPDATE: 'PATIENT_UPDATE',

    PRESCRIPTION_CREATE: 'PRESCRIPTION_CREATE',
    PRESCRIPTION_READ: 'PRESCRIPTION_READ',

    LAB_CREATE: 'LAB:CREATE',
    LAB_READ: 'LAB:READ',
    LAB_UPDATE: 'LAB:UPDATE',

    VITALS_CREATE: 'VITALS:CREATE',
    VITALS_READ: 'VITALS:READ',

    APPOINTMENT_CREATE: 'APPOINTMENT:CREATE',
    APPOINTMENT_READ: 'APPOINTMENT:READ',
    APPOINTMENT_UPDATE: 'APPOINTMENT:UPDATE',

    MENU_VIEW: 'MENU_VIEW',
};

module.exports = {
    PERMISSIONS,
};
